
    var data = [{
        category: "T-Shirts",
        name: "S-5XL Vintage Women Cotton Loose Color Print Long Sleeve Blouse - 6 Blue",
        image: "https://imgaz2.staticbg.com/thumb/large/oaupload/ser1/banggood/images/07/24/58358579-cb22-4f68-82d7-a87af85a0c4f.jpg.webp",
        review: "22 reviews",
        discount: "2,037.99",
        off: "11% Off",
        price: "1808.45",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Women Cute Cartoon Cat Letter Print O-Neck Casual Short Sleeve T-Shirts - Grey S",
        image: "https://imgaz.staticbg.com/thumb/large/oaupload/banggood/images/53/71/f48492fd-0a34-497f-bb71-bea0a2ff80fe.jpg.webp",
        review: "5 reviews",
        discount: "1,282.90",
        off: "47% Off",
        price: "678.83",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Solid Color V-neck Cross Straps Off Shoulder Short Sleeve T-shirts - S Black",
        image: "https://imgaz.staticbg.com/thumb/large/oaupload/ser1/banggood/images/E9/C8/50e0e470-cae0-4446-a8f9-7e73cb4a994f.jpeg.webp",
        review: "1 review",
        discount: "2,264.52",
        off: "51% Off",
        price: "1104.70",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Women Moon Graphics Round Neck Casual Short Sleeve T-Shirts - Black M",
        image: "https://imgaz1.staticbg.com/thumb/large/oaupload/banggood/images/CF/9F/0adde70d-99fb-4846-a0cd-1a4282e322f3.jpg.webp",
        review: "0 review",
        discount: "1,355.39",
        off: "17% Off",
        price: "1129.37",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Women Moon Graphics Round Neck Casual Short Sleeve T-Shirts - Black M",
        image: "https://imgaz.staticbg.com/thumb/large/oaupload/ser1/banggood/images/8A/9D/e95351bc-e243-4a72-a9ae-5a8f4ec11914.jpg.webp",
        review: "5 reviews",
        discount: "1360.40",
        off: "31% Off",
        price: "755",
        deals: "Upgrade Deals"
    }, {
        category: "T-Shirts",
        name: "Women Knit Long Sleeve Zipper Casual Square Collar Basic T-Shirts - S Black",
        image: "https://imgaz2.staticbg.com/thumb/large/oaupload/ser1/banggood/images/CB/15/dc6b8ee8-7520-4a2f-8246-424655c57d80.jpeg.webp",
        review: "0 review",
        discount: "2,560.86",
        off: "21% Off",
        price: "1843.60",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Casual Women Patchwork Long Sleeve Crew Neck Hign Low Hem Shirts - 6 As Picture",
        image: "https://imgaz1.staticbg.com/thumb/large/oaupload/ser1/banggood/images/30/85/909c2480-9538-4a50-b56b-dd1ad862247d.jpg.webp",
        review: "3 reviews",
        discount: "1,813.37",
        off: "9% Off",
        price: "1643.08",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Sportswear Suit Women's Season New Wave Casual Loose Denim Short-sleeved Trousers Large Size Two-piece - L Red strip",
        image: "https://imgaz2.staticbg.com/thumb/large/oaupload/banggood/images/92/E1/9ddb0fd3-e250-40a8-9d40-d54352174e69.jpg.webp",
        review: "6 reviews",
        discount: "6,651.09",
        off: "17% Off",
        price: "5517.21",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "A328 New Fashion Sports And Leisure Suit Loose Ocean Net Red Short Coat Casual Pants Two-piece - Photo Color S",
        image: "https://imgaz.staticbg.com/thumb/large/oaupload/banggood/images/5E/F8/2ba36684-cfa9-4513-88d5-584a8b44c885.jpg.webp",
        review: "6 reviews",
        discount: "5139.78",
        off: "18% Off",
        price: "4132.20",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Large Size Women's Art Retro Silk Printing Irregular Green Long Loose Wide Leg Pants Two-piece Suit - 2XL Green",
        image: "https://imgaz1.staticbg.com/thumb/large/oaupload/banggood/images/F0/6C/2fa7211d-9e12-4308-9025-66bffd98dc6a.jpg.webp",
        review: "5 reviews",
        discount: "4,836.91",
        off: "17% Off",
        price: "4005.44",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Women Casual Cartoon Embroidery Half Sleeve T-Shirts - One Size Red",
        image: "https://imgaz2.staticbg.com/thumb/large/oaupload/banggood/images/FB/73/9f60f168-35d8-49e6-9e1f-939479fb0127.jpg.webp",
        review: "10 reviews",
        discount: "4,005.44",
        off: "31% Off",
        price: "2765.78",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Floral Print Color Block Loose Round neck Short Sleeve Knitted T-Shirt - Multicolor",
        image: "https://imgaz1.staticbg.com/thumb/large/oaupload/banggood/images/11/BB/5f56d43c-46c0-4a0a-9cc7-a822b68af3ec.jpg.webp",
        review: "1 review",
        discount: "3778.81",
        off: "41% Off",
        price: "2191.31",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Temperament Ladies Women's New Loose Flocking Flower Coat Wide-leg Pants Two-piece Fashion Suit Women - S Black",
        image: "https://imgaz.staticbg.com/thumb/large/oaupload/banggood/images/9D/A3/845a336e-e36d-4384-938b-012c71dd21d1.jpg.webp",
        review: "1 review",
        discount: "3,551.91",
        off: "17% Off",
        price: "2947.20",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Season New Casual Sports Suit Female Loose Thin Wide Leg Pants Sportswear Suit Two-piece - white XXL",
        image: "https://imgaz1.staticbg.com/thumb/large/oaupload/banggood/images/5E/3E/5c7f01fb-8c13-4b31-9d87-118df40da80e.jpg.webp",
        review: "3 reviews",
        discount: "3,476.32",
        off: "16% Off",
        price: "2871.61",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Season New Fashion Casual Large Size Striped Wide Leg Shorts Two-piece Slimming Net Red Suit Female - Blue XL",
        image: "https://imgaz1.staticbg.com/thumb/large/oaupload/banggood/images/2F/75/71461c5b-5afb-44f4-903d-dd8ec268cd78.jpg.webp",
        review: "9 reviews",
        discount: "3,476.32",
        off: "17% Off",
        price: "2871.61",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Women's New Suit Fashion Loose Thin Temperament Season Goddess Wide Leg Pants Two Sets Of Tide - L Black",
        image: "https://imgaz3.staticbg.com/thumb/large/oaupload/banggood/images/32/1C/60b152be-5b0b-4edf-92ec-3ef9f9655858.jpg.webp",
        review: "11 reviews",
        discount: "3,476.32",
        off: "17% Off",
        price: "2871.61",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Season New Women's Black Two-piece Wide Leg Pants Printing Suit Casual Fashion Suit Female Large Size - S Black",
        image: "https://imgaz2.staticbg.com/thumb/large/oaupload/banggood/images/B4/B9/f1c1804e-427b-42ab-bf62-293ade45ab1a.jpg.webp",
        review: "9 reviews",
        discount: "3,476.32",
        off: "17% Off",
        price: "2871.61",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Season New Loose Irregular Short-sleeved T-shirt Suit Elastic Waist Wide Leg Pants Two Sets Of Large Size Women's Clothing - One Size Blue",
        image: "https://imgaz3.staticbg.com/thumb/large/oaupload/banggood/images/1D/33/3a5af2cc-ca9b-4078-84c6-711449cac3d8.jpg.webp",
        review: "0 review",
        discount: "3,400.81",
        off: "18% Off",
        price: "2796.02",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Net Red Season New Girl Love Printing Sweater Two-piece Fashion Skirt Suit Tide - Yellow S",
        image: "https://imgaz2.staticbg.com/thumb/large/oaupload/banggood/images/DD/1E/30ee8014-9f6b-42eb-9068-4e43f4339b05.jpg.webp",
        review: "4 reviews",
        discount: "3,400.81",
        off: "18% Off",
        price: "2796.02",
        deals: "Upgrade Deals",
    }, {
        category: "T-Shirts",
        name: "Women Letter Pattern Casual V-Neck Long Sleeve T-Shirts - Dark Grey M",
        image: "https://imgaz2.staticbg.com/thumb/large/oaupload/banggood/images/68/C1/086d945a-9feb-48a9-b3d4-8a899a9bc99c.jpg.webp",
        review: "5 reviews",
        discount: "3,325.14",
        off: "55% Off",
        price: "1511.02",
        deals: "Upgrade Deals",
    }, ]
    localStorage.setItem("womens_data", JSON.stringify(data))
